local map = vim.keymap.set
local opts = { noremap = true, silent = true }

map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<CR>", vim.tbl_extend("force", opts, { desc = "Toggle trouble diagnostics" }))
map("n", "<leader>e", "<cmd>Neotree toggle<CR>", vim.tbl_extend("force", opts, { desc = "Toggle file tree" }))
map("n", "<leader>ff", function() require("telescope.builtin").find_files() end, vim.tbl_extend("force", opts, { desc = "Find files" }))
map("n", "<leader>fg", function() require("telescope.builtin").live_grep() end, vim.tbl_extend("force", opts, { desc = "Live grep" }))
map("n", "<leader>wv", "<cmd>vsplit<CR>", vim.tbl_extend("force", opts, { desc = "Vertical split" }))
map("n", "<leader>ws", "<cmd>split<CR>", vim.tbl_extend("force", opts, { desc = "Horizontal split" }))
map("n", "<leader>wc", "<cmd>close<CR>", vim.tbl_extend("force", opts, { desc = "Close window" }))
map("n", "<leader>wh", "<C-w>h", vim.tbl_extend("force", opts, { desc = "Window left" }))
map("n", "<leader>wj", "<C-w>j", vim.tbl_extend("force", opts, { desc = "Window down" }))
map("n", "<leader>wk", "<C-w>k", vim.tbl_extend("force", opts, { desc = "Window up" }))
map("n", "<leader>wl", "<C-w>l", vim.tbl_extend("force", opts, { desc = "Window right" }))
map("n", "<leader>ww", "<C-w>w", vim.tbl_extend("force", opts, { desc = "Cycle windows" }))
map("n", "<leader>w=", "<C-w>=", vim.tbl_extend("force", opts, { desc = "Balance windows" }))
map("n", "<leader>q", "<cmd>qa<CR>", vim.tbl_extend("force", opts, { desc = "Quit all" }))
map({ "i", "n" }, "<C-s>", function()
  require("conform").format({ async = false, lsp_fallback = true })
  vim.cmd("w")
end, vim.tbl_extend("force", opts, { desc = "Format and save" }))
map("n", "<leader>h", "<cmd>nohlsearch<CR>", vim.tbl_extend("force", opts, { desc = "Clear search highlights" }))
map("n", "<leader>gt", "<cmd>tabnew<CR>", vim.tbl_extend("force", opts, { desc = "New tab" }))
map("n", "<C-t>", "<cmd>tabnew<CR>", vim.tbl_extend("force", opts, { desc = "New tab" }))
map("n", "<leader>gg", "<cmd>LazyGit<CR>", vim.tbl_extend("force", opts, { desc = "Toggle lazygit" }))
map("n", "<leader>li", "<cmd>checkhealth vim.lsp<CR>", vim.tbl_extend("force", opts, { desc = "LSP health" }))
map("n", "]d", function() vim.diagnostic.goto_next() end, vim.tbl_extend("force", opts, { desc = "Next diagnostic" }))
map("n", "[d", function() vim.diagnostic.goto_prev() end, vim.tbl_extend("force", opts, { desc = "Previous diagnostic" }))
